nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https://www.trocservices.fr']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['Link']
        max_age: 360000
    paths:
        '^/': null