twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        image_dir: '/images/backoffice-image/'
        css_dir: 'css'
        upload_dir: 'img/'


when@test:
    twig:
        strict_variables: true

