vich_uploader:
    db_driver: orm
    


    mappings:
        image:
            uri_prefix: /images/image
            upload_destination: '%kernel.project_dir%/public/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
