vich_uploader:
    db_driver: orm
    


    mappings:
        image_profile:
            uri_prefix: /images/picture
            upload_destination: '%kernel.project_dir%/public/images/picture'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
